version: "3"
services:
    web:
        build: .
        ports:
            - "8000:80"
        depends_on:
            - db
            - cache
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
    cache:
        image: "redis"